services:

  database:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
      - 33060


  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "8080:8080"


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USERNAME: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      DB_NAME: ${MARIADB_DATABASE}
    ports:
      - "5000:5000"
    depends_on:
      - database


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "3001:3000"
    depends_on:
      - backend


volumes:
  db_data:
